<?php

namespace VMBundle\Repository;

use VMBundle\Entity\Transaction;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSumOfTransaction($type, $staus)
    {
        $em = $this->getEntityManager();
        $dql = "SELECT SUM(t.coinDenomination) AS res FROM VMBundle\Entity\Transaction t WHERE  t.type = ?1 and t.status = ?2";
        return $em->createQuery($dql)
            ->setParameter(1, $type)
            ->setParameter(2, $staus)
            ->getSingleScalarResult();
    }

    public function getInjectedTransactions()
    {
        $em = $this->getEntityManager();
        return $em->getRepository("VMBundle:Transaction")->findBy(
            [
                'status' => Transaction::STATUS_INJECTED,
                'type' => Transaction::TYPE_INPUT,
            ]
        );
    }
}
